language: python

python:
  - "2.7"
  
before_install:
  # Need bower package manager for installing
  # client-side dependancies.
  - npm install -g bower

install:
  # Client-side dependencies.
  - cd complexity/assets
  - bower install
  - cd ../..
  
  # Server-side dependencies.
  - npm install -g coffee less
  - pip install -r requirements.txt
  
before_script:
  # Create secrets.py and install python package.
  - fab create_secrets
  - python setup.py develop
  
script:
  # Runs complexity.tests
  - python setup.py test
