language: python

python:
  - "2.7"
  
install:
  - npm install -g bower
  - npm install -g coffee
  - npm install -g less
  
  - cd complexity/assets
  - bower install
  
  - cd bower_components/katex
  - npm install browserify
  - make build/katex.js
  - cd ../../../../
  
  - pip install -r requirements.txt
  
before_script:
  - fab create_secrets
  - python setup.py develop
  
script:
  - python setup.py test
